#!/bin/sh
#共通ヘッダファイル

#ディレクトリ
ANSWER=./answer
QUESTION=./question
MASTER=./master
LOG=./log
SCORE=./score
LOGIN=./login

#集計用ファイル
RESULT=./total.result

#人数ファイル
P_NO_FILE=${MASTER}/player_no

#得点集計ファイル
RESULT=./total.result

#得点の重み
POINT_LIST=( 0 10 5 3 2 1 )

#問題数
Q_NO=10

#個数
#NO_ARRAY=(  3 10 20 )
NO_ARRAY=(  3 10 20  7 14 10 15 20 123 110 )

#段数
#DAN_ARRAY=( 1  1  2 )
DAN_ARRAY=( 1  1  2  2  3  3  4  4   5   5 )

