#!/bin/sh
## for Mac OS X only
##
## Usage
## gitpullreq
##   Open GitHub pull request page compare current branch and develop.
##   You need to have branch name "develop".
##
## gitpullreq "base branch"
##   ex. gitpullreq master
##   then open GitHub pull request page compare current branch and base branch by browser.

GITHUB="https://github.com"
SAFARI="/Applications/Safari.app"
CHROME="/Applications/Google Chrome.app/"
FF="/Applications/Firefox.app"

# set your github repository
REPOSITORY="kitchhike/kitchhike"
# set your browser
BROWSER=$CHROME

BASE=$1
if [ ! -n "$BASE" ]; then
  BASE="develop"
fi
CURRENT=`git symbolic-ref --short HEAD`

open -a "$BROWSER" $GITHUB/$REPOSITORY/compare/$BASE...$CURRENT
